### PR TITLE
Add xray_trace_id option to provide the X-Amzn-Trace-Id header

### PR DESCRIPTION
**Pull request by james-bowers**
This PR aims to enable the ability to invoke a lambda and pass through the trace id value required for AWS Xray.

https://aws.amazon.com/xray/

### CODE REVIEW

**Comment by james-bowers** [comment]
Also requires https://github.com/ex-aws/ex_aws/pull/668

**Comment by samfrench** [comment]
Is there any update on getting this PR merged? I see the one this requires was merged 6 months ago.

**Comment by MattLongCode** [comment]
> Is there any update on getting this PR merged? I see the one this requires was merged 6 months ago.

@samfrench yes would be good to get it merged. It's better to get it merged and then replace the line here https://github.com/bbc/belfrage/blob/b0b63430c9f088c1fad15eee60ccfdf20d410c56/mix.exs#L60 to point to ex_aws/ex_aws_lambda

Less burden to maintain it, and less risk as it is then owned by the BBC repo.

It's just something we haven't got around to doing.

**Comment by MattLongCode** [comment]
@benwilson512 Please can you review this, @bbc would appreciate it.

**Review by MattLongCode — APPROVED** [review]

**Comment by benwilson512** [comment]
@MattLongCode Hi Matt, I am no longer the maintainer of ExAws. @bernardd is the fellow you want to reach out to.

**Review by bernardd — APPROVED** [review]

**Comment by bernardd** [comment]
Hi hello! I'm still learning which of these sub-modules I'm meant to be responsible for :)
@MattLongCode Tell @bbc that I'll merge it, but only if they bring back Sue Perkins as a presenter on Great British Bake Off.

It looks fine to me :)

**Comment by james-bowers** [comment]
> Hi hello! I'm still learning which of these sub-modules I'm meant to be responsible for :)
> @MattLongCode Tell @bbc that I'll merge it, but only if they bring back Sue Perkins as a presenter on Great British Bake Off.
> 
> It looks fine to me :)

Thanks for merging! We'll contact Channel 4 for you 🤞🏼

**Pull request merged**
