### PR TITLE
feat: allow custom parser as opts for invoke/4

### PR DESCRIPTION
**Pull request by jokawachi-hg**

### CODE REVIEW

**Comment by bernardd** [comment]
Thanks @jokawachi-hg! Just as a request for next time, if you can run `mix format` over your PR before opening it, that saves me some time.

**Comment by jokawachi-hg** [comment]
> Thanks @jokawachi-hg! Just as a request for next time, if you can run `mix format` over your PR before opening it, that saves me some time.

@bernardd I'm really sorry for the inconvenience! I had intended to open the PR for an internal review and should've caught the formatting. I really appreciate you taking a look so quickly!

**Comment by bernardd** [comment]
No drama :) You got lucky with the timing - I was like two months behind on PRs and just happened to pick yesterday to catch up :)

**Comment by jokawachi-hg** [comment]
> No drama :) You got lucky with the timing - I was like two months behind on PRs and just happened to pick yesterday to catch up :)

Sweet! Thanks again @bernardd! :)

**Pull request merged**
